import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/shared";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Space Time Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-veryDarkBlue text-white">
      <body className={`${inter.className} `}>
        <div className="max-w-[1440px] mx-auto grid grid-cols-mob lgMob:grid-cols-tab lap:grid-cols-lap desk:grid-cols-desk">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
